# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 20:31
from __future__ import unicode_literals

from django.db import migrations

FACEBOOK_CLIENT_ID = '490190401188102'
FACEBOOK_KEY = '20ad49bd8c42b795d22edce0c7307543'


def add_facebook_social_app(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')

    if Site.objects.count() == 0:
        site = Site()
        site.domain = "example.com"
        site.name = "example.com"
        site.save()
    else:
        site = Site.objects.first()

    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    app = SocialApp()
    app.provider = 'facebook'
    app.name = 'facebook'
    app.user_id = 1
    app.client_id = FACEBOOK_CLIENT_ID
    app.secret = FACEBOOK_KEY
    app.save()
    app.sites = [site.id]
    app.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_facebook_social_app,reverse_func),
    ]
