# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_auto_20160824_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battle',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='fighter',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
