# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_fighter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
