# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arena', '0003_auto_20160926_0021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='battle',
            unique_together=set([('fighter_one', 'fighter_two')]),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('battle', 'voter')]),
        ),
    ]
