# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-03 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_auto_20161014_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='image',
            field=models.ImageField(upload_to='arena/static/uploads'),
        ),
    ]
